name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Build and test with Rake
      run: |
        gem install bundler -v "~> 2.4"
        bundle install --jobs 4 --retry 3
        bundle exec middleman build --clean
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      env:
        BRANCH: "gh-pages"
        FOLDER: "build"
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
